import { createHash } from 'node:crypto';
import { SYBASE_READ_ONLY_REASON } from '../../../shared/engine-capabilities';
import type {
  Connection,
  DatabaseObjectDefinition,
  DatabaseObjectPlan,
} from '../../../shared/types';
import type { SqlAdapter } from '../../database/adapter';
import { SqlBuilder } from '../../database/sql-builder';
import { assertSingleStatement } from '../../security/single-statement';
import {
  assertSqliteTrigger,
  keyword,
  mysqlIndexClause,
  objectHeader,
  sameIdentifier,
  sqlTokens,
} from '../../database/object-sql';
import { listDatabaseObjects } from './database-metadata';
import { renameDefinition } from '../../database/rename-definition';
import { aseDefinition, aseIndex } from '../../database/adapters/sybase/sybase-catalog';
import type { IndexOptions } from '../../../shared/index-options';
import {
  readIndexMetadata,
  validateIndexOptions,
  rewriteIndexSql,
  indexCommentStatements,
} from '../../database/index-options';

export interface ObjectRef {
  connectionId: string;
  database?: string;
  schema: string;
  table: string;
  objectName: string;
  kind: 'index' | 'trigger';
}
interface Details extends DatabaseObjectDefinition {
  restore: string[];
  prefix: string[];
  suffix: string[];
  catalog?: unknown;
}
const options = { limit: 5000, timeout: 30000, readOnly: true };
const literal = (s: string) => "'" + s.replaceAll("'", "''") + "'";
const nliteral = (s: string) => 'N' + literal(s);

export async function readObjectDefinition(
  adapter: SqlAdapter,
  connection: Connection,
  ref: ObjectRef,
): Promise<Details> {
  const object = (
    await listDatabaseObjects(adapter, connection, ref.kind, {
      schema: ref.schema,
      table: ref.table,
      name: ref.objectName,
    })
  ).find((o) => o.name === ref.objectName && o.schema === ref.schema && o.table === ref.table);
  if (!object) throw new Error('Object no longer exists or is not accessible.');
  const builder = new SqlBuilder(connection.engine);
  const q = (name: string) => builder.quote(name);
  const table = builder.table(ref),
    qualified = builder.table({ schema: ref.schema, table: ref.objectName });
  const result: Details = {
    ...object,
    engine: connection.engine,
    version: '',
    editableSql: object.definition ?? '',
    notice: 'Changes rebuild this object in a transaction. The table may be locked while applying.',
    restore: [],
    prefix: [],
    suffix: [],
  };
  if (!object.definition)
    result.readOnlyReason = 'Definition unavailable or generated by the database.';
  if (connection.engine === 'sybase') {
    result.notice = SYBASE_READ_ONLY_REASON;
    if (ref.kind === 'index') {
      const index = await aseIndex(adapter, ref);
      result.editableSql = index.sql;
      result.catalog = index.raw;
      result.readOnlyReason = index.readOnlyReason;
    } else {
      result.editableSql = (
        await aseDefinition(adapter, { schema: ref.schema, table: ref.objectName })
      ).replace(/^\s*CREATE\s+OR\s+REPLACE\s+/i, 'CREATE ');
      result.readOnlyReason = result.editableSql
        ? undefined
        : 'The server did not return a complete trigger definition.';
    }
    result.readOnlyReason = SYBASE_READ_ONLY_REASON;
  }
  if (connection.engine === 'postgres') {
    const b = new SqlBuilder('postgres');
    if (ref.kind === 'index') {
      const row = (
        await adapter.query(
          `SELECT c.relkind, i.indisreplident, i.indisclustered, EXISTS(SELECT 1 FROM pg_constraint WHERE conindid=c.oid) AS constrained, EXISTS(SELECT 1 FROM pg_inherits WHERE inhrelid=c.oid) AS inherited, obj_description(c.oid) AS comment FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_index i ON i.indexrelid=c.oid WHERE n.nspname=${b.bind(ref.schema)} AND c.relname=${b.bind(ref.objectName)}`,
          [ref.schema, ref.objectName],
          options,
        )
      ).rows[0];
      if (!row || row.constrained || row.inherited || row.indisreplident || row.relkind !== 'i')
        result.readOnlyReason =
          'Constraint, partition or replica-identity indexes must be managed with their table.';
      if (row?.comment != null)
        result.suffix.push(`COMMENT ON INDEX ${qualified} IS ${literal(String(row.comment))}`);
      if (row?.indisclustered)
        result.suffix.push(`ALTER TABLE ${table} CLUSTER ON ${q(ref.objectName)}`);
    } else {
      const row = (
        await adapter.query(
          "SELECT t.tgenabled, obj_description(t.oid, 'pg_trigger') AS comment FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=$1 AND c.relname=$2 AND t.tgname=$3",
          [ref.schema, ref.table, ref.objectName],
          options,
        )
      ).rows[0];
      if (row?.tgenabled && row.tgenabled !== 'O')
        result.suffix.push(
          `ALTER TABLE ${table} ${row.tgenabled === 'D' ? 'DISABLE' : row.tgenabled === 'A' ? 'ENABLE ALWAYS' : 'ENABLE REPLICA'} TRIGGER ${q(ref.objectName)}`,
        );
      if (row?.comment != null)
        result.suffix.push(
          `COMMENT ON TRIGGER ${q(ref.objectName)} ON ${table} IS ${literal(String(row.comment))}`,
        );
      result.notice =
        'Changes rebuild the trigger in a transaction. The referenced PostgreSQL function is edited separately.';
      if (/^CREATE CONSTRAINT TRIGGER\b/i.test(result.editableSql))
        result.readOnlyReason = 'Constraint triggers must be managed with their table constraints.';
    }
  }
  if (connection.engine === 'mysql') {
    result.notice =
      'MySQL / MariaDB DDL commits implicitly. Index changes use one ALTER TABLE. Trigger replacement has a gap; if creation fails, the old definition is restored when possible.';
    if (ref.kind === 'index') {
      if (ref.objectName === 'PRIMARY')
        result.readOnlyReason = 'Primary key indexes must be managed with their table constraint.';
      else {
        const row = (await adapter.query(`SHOW CREATE TABLE ${table}`, [], options)).rows[0];
        const create = String(row?.['Create Table'] ?? '');
        const mode = String(
          (await adapter.query('SELECT @@SESSION.sql_mode AS sql_mode', [], options)).rows[0]
            ?.sql_mode ?? '',
        );
        result.mysqlNoBackslashEscapes = mode.split(',').includes('NO_BACKSLASH_ESCAPES');
        result.prefix.push(`SET SESSION sql_mode = ${literal(mode)}`);
        result.editableSql = mysqlIndexClause(
          create,
          ref.objectName,
          result.mysqlNoBackslashEscapes,
        );
        result.readOnlyReason = undefined;
      }
    } else {
      const row = (await adapter.query(`SHOW CREATE TRIGGER ${qualified}`, [], options)).rows[0];
      result.editableSql = String(row?.['SQL Original Statement'] ?? '');
      if (!result.editableSql)
        result.readOnlyReason = 'The server did not return a complete trigger definition.';
      else result.readOnlyReason = undefined;
      // Re-creation uses the original SQL mode, character set and collation.
      for (const [field, variable] of [
        ['sql_mode', 'sql_mode'],
        ['character_set_client', 'character_set_client'],
        ['collation_connection', 'collation_connection'],
      ] as const)
        if (row?.[field] != null)
          result.prefix.push(`SET SESSION ${variable} = ${literal(String(row[field]))}`);
      // Preserve firing order by explicitly placing the replacement before its
      // next sibling (or after its previous sibling).
      const siblings = (
        await adapter.query(
          'SELECT TRIGGER_NAME AS name, ACTION_TIMING AS timing, EVENT_MANIPULATION AS event, ACTION_ORDER AS position FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA=? AND EVENT_OBJECT_TABLE=? ORDER BY ACTION_ORDER',
          [ref.schema, ref.table],
          options,
        )
      ).rows;
      const current = siblings.find((r) => r.name === ref.objectName);
      const ordered = siblings.filter(
        (r) => r.timing === current?.timing && r.event === current?.event,
      );
      const index = ordered.findIndex((r) => r.name === ref.objectName);
      const next = ordered[index + 1],
        previous = ordered[index - 1];
      const tokens = sqlTokens(result.editableSql, 'mysql');
      const forRow = tokens.findIndex(
        (token, i) =>
          keyword(token, 'FOR') && keyword(tokens[i + 1], 'EACH') && keyword(tokens[i + 2], 'ROW'),
      );
      if (forRow >= 0) {
        const rowEnd = tokens[forRow + 2].end;
        const hasOrder =
          keyword(tokens[forRow + 3], 'PRECEDES') || keyword(tokens[forRow + 3], 'FOLLOWS');
        const bodyStart = hasOrder ? tokens[forRow + 4].end : rowEnd;
        const clause =
          next || previous
            ? ` ${next ? 'PRECEDES' : 'FOLLOWS'} ${q(String((next ?? previous).name))}`
            : '';
        result.editableSql =
          result.editableSql.slice(0, rowEnd) +
          clause +
          ' ' +
          result.editableSql.slice(bodyStart).trimStart();
      }
    }
  }
  if (connection.engine === 'sqlserver') {
    result.notice =
      'Index changes may rebuild the index; triggers use ALTER TRIGGER. Changes run in a transaction.';
    if (ref.kind === 'trigger') {
      const row = (
        await adapter.query(
          `SELECT t.is_disabled, m.uses_ansi_nulls, m.uses_quoted_identifier, OBJECTPROPERTY(t.object_id, 'ExecIsFirstInsertTrigger') AS first_insert, OBJECTPROPERTY(t.object_id, 'ExecIsLastInsertTrigger') AS last_insert, OBJECTPROPERTY(t.object_id, 'ExecIsFirstUpdateTrigger') AS first_update, OBJECTPROPERTY(t.object_id, 'ExecIsLastUpdateTrigger') AS last_update, OBJECTPROPERTY(t.object_id, 'ExecIsFirstDeleteTrigger') AS first_delete, OBJECTPROPERTY(t.object_id, 'ExecIsLastDeleteTrigger') AS last_delete FROM sys.triggers t JOIN sys.sql_modules m ON m.object_id=t.object_id WHERE t.object_id=OBJECT_ID(@p1)`,
          [qualified],
          options,
        )
      ).rows[0];
      if (!ref.table || !row)
        result.readOnlyReason =
          'Only visible T-SQL table/view trigger definitions can be edited here.';
      const moduleTokens = sqlTokens(result.editableSql, 'sqlserver');
      const first = moduleTokens[0];
      const createOrAlter =
        keyword(first, 'CREATE') &&
        keyword(moduleTokens[1], 'OR') &&
        keyword(moduleTokens[2], 'ALTER');
      if (first && (keyword(first, 'ALTER') || createOrAlter)) {
        const end = createOrAlter ? moduleTokens[2].end : first.end;
        result.editableSql =
          result.editableSql.slice(0, first.start) + 'CREATE' + result.editableSql.slice(end);
      }
      if (row)
        result.prefix = [
          `SET ANSI_NULLS ${row.uses_ansi_nulls ? 'ON' : 'OFF'}`,
          `SET QUOTED_IDENTIFIER ${row.uses_quoted_identifier ? 'ON' : 'OFF'}`,
        ];
      for (const event of ['insert', 'update', 'delete']) {
        for (const order of ['first', 'last'])
          if (row?.[`${order}_${event}`])
            result.suffix.push(
              `EXEC sys.sp_settriggerorder @triggername=${nliteral(qualified)}, @order=${literal(order.toUpperCase())}, @stmttype=${literal(event.toUpperCase())}`,
            );
      }
      if (row?.is_disabled) result.suffix.push(`DISABLE TRIGGER ${qualified} ON ${table}`);
    } else {
      const rows = (
        await adapter.query(
          `SELECT i.*, st.no_recompute, ds.name AS space_name, ds.type AS space_type, c.name AS column_name, ic.key_ordinal, ic.is_descending_key, ic.is_included_column, p.data_compression_desc FROM sys.indexes i JOIN sys.stats st ON st.object_id=i.object_id AND st.stats_id=i.index_id JOIN sys.index_columns ic ON ic.object_id=i.object_id AND ic.index_id=i.index_id JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id LEFT JOIN sys.data_spaces ds ON ds.data_space_id=i.data_space_id LEFT JOIN sys.partitions p ON p.object_id=i.object_id AND p.index_id=i.index_id AND p.partition_number=1 WHERE i.object_id=OBJECT_ID(@p1) AND i.name=@p2 ORDER BY ic.is_included_column, ic.key_ordinal, ic.index_column_id`,
          [table, ref.objectName],
          options,
        )
      ).rows;
      const r = rows[0];
      if (
        !r ||
        ![1, 2].includes(Number(r.type)) ||
        r.is_primary_key ||
        r.is_unique_constraint ||
        r.space_type !== 'FG'
      )
        result.readOnlyReason =
          'Constraint, partitioned or specialized indexes must be managed with their table or engine-specific DDL.';
      else {
        const keys = rows
          .filter((c) => !c.is_included_column && Number(c.key_ordinal) > 0)
          .map((c) => `${q(String(c.column_name))} ${c.is_descending_key ? 'DESC' : 'ASC'}`);
        const included = rows
          .filter((c) => c.is_included_column)
          .map((c) => q(String(c.column_name)));
        result.editableSql = `CREATE ${r.is_unique ? 'UNIQUE ' : ''}${Number(r.type) === 1 ? 'CLUSTERED' : 'NONCLUSTERED'} INDEX ${q(ref.objectName)} ON ${table} (${keys.join(', ')})${included.length ? ` INCLUDE (${included.join(', ')})` : ''}${r.has_filter ? ` WHERE ${r.filter_definition}` : ''}\nWITH (DROP_EXISTING = ON, ${Number(r.fill_factor) ? `FILLFACTOR = ${Number(r.fill_factor)}, ` : ''}PAD_INDEX = ${r.is_padded ? 'ON' : 'OFF'}, IGNORE_DUP_KEY = ${r.ignore_dup_key ? 'ON' : 'OFF'}, ALLOW_ROW_LOCKS = ${r.allow_row_locks ? 'ON' : 'OFF'}, ALLOW_PAGE_LOCKS = ${r.allow_page_locks ? 'ON' : 'OFF'}, STATISTICS_NORECOMPUTE = ${r.no_recompute ? 'ON' : 'OFF'}, ${r.optimize_for_sequential_key != null ? `OPTIMIZE_FOR_SEQUENTIAL_KEY = ${r.optimize_for_sequential_key ? 'ON' : 'OFF'}, ` : ''}DATA_COMPRESSION = ${r.data_compression_desc}) ON ${q(String(r.space_name))}`;
        result.readOnlyReason = undefined;
        if (r.is_disabled)
          result.suffix.push(`ALTER INDEX ${q(ref.objectName)} ON ${table} DISABLE`);
      }
    }
  }
  // sp_rename changes catalog names but does not rewrite module source headers.
  if (
    ref.kind === 'trigger' &&
    result.editableSql &&
    !result.readOnlyReason &&
    ['sqlserver', 'sybase'].includes(connection.engine)
  ) {
    result.editableSql = renameDefinition(
      result.editableSql,
      connection.engine,
      'trigger',
      qualified,
    );
    const header = objectHeader(result.editableSql, connection.engine, 'trigger');
    result.editableSql =
      result.editableSql.slice(0, header.tableStart) +
      table +
      result.editableSql.slice(header.tableEnd);
  }
  result.restore = [result.editableSql];
  if (ref.kind === 'index') await readIndexMetadata(adapter, result);
  if (ref.kind === 'index' && connection.engine === 'sqlserver') {
    // Switching clustered/nonclustered creates a new index id and drops its extended properties.
    // Restore the managed description for both structured and raw SQL edits.
    if (result.indexOptions?.comment)
      result.suffix.push(
        ...indexCommentStatements('sqlserver', result, result.indexOptions.comment),
      );
    const custom = (
      await adapter.query(
        "SELECT e.name FROM sys.extended_properties e JOIN sys.indexes i ON i.object_id=e.major_id AND i.index_id=e.minor_id WHERE e.class=7 AND i.object_id=OBJECT_ID(@p1) AND i.name=@p2 AND e.name<>N'MS_Description'",
        [table, ref.objectName],
        options,
      )
    ).rows;
    if (custom.length)
      result.readOnlyReason =
        'Indexes with custom extended properties require an explicit property preservation plan.';
  }
  result.version = createHash('sha256')
    .update(
      JSON.stringify({
        sql: result.editableSql,
        prefix: result.prefix,
        suffix: result.suffix,
        reason: result.readOnlyReason,
        catalog: result.catalog,
        indexOptions: result.indexOptions,
        mysqlNoBackslashEscapes: result.mysqlNoBackslashEscapes,
      }),
    )
    .digest('hex');
  return result;
}

export function planObjectChange(
  detail: Details,
  ref: ObjectRef,
  sql: string | IndexOptions,
): DatabaseObjectPlan {
  if (detail.readOnlyReason) throw new Error(detail.readOnlyReason);
  if (typeof sql !== 'string') {
    if (ref.kind !== 'index' || !detail.indexOptions || !detail.indexCapabilities)
      throw new Error('Index options are unavailable for this object.');
    const patch = { ...sql };
    const merged = { ...detail.indexOptions, ...patch };
    if (patch.type && patch.type !== detail.indexOptions.type && patch.method === undefined) {
      merged.method = ['FULLTEXT', 'SPATIAL'].includes(patch.type)
        ? ''
        : detail.indexOptions.method || detail.indexCapabilities.methods[0]?.name;
      patch.method = merged.method;
    }
    if (patch.method === '' && !['FULLTEXT', 'SPATIAL'].includes(merged.type ?? '')) {
      patch.method = merged.method = detail.indexCapabilities.defaultMethod;
    }
    validateIndexOptions(merged, detail.indexCapabilities, detail.engine);
    for (const key of Object.keys(patch) as (keyof IndexOptions)[])
      if (patch[key] === detail.indexOptions[key]) delete patch[key];
    if (!Object.keys(patch).length) throw new Error('There are no index option changes.');
    const rebuild =
      patch.type !== undefined ||
      patch.method !== undefined ||
      (detail.engine === 'mysql' && patch.comment !== undefined);
    const plan = rebuild
      ? planObjectChange(
          detail,
          ref,
          rewriteIndexSql(detail.editableSql, detail.engine, patch, detail.mysqlNoBackslashEscapes),
        )
      : { statements: [], atomic: true, notice: 'Changes run in one transaction.' };
    if (patch.comment !== undefined)
      plan.statements.push(...indexCommentStatements(detail.engine, detail, patch.comment));
    return plan;
  }
  if (!sql.trim()) throw new Error('The definition cannot be empty.');
  const engine = detail.engine,
    b = new SqlBuilder(engine),
    q = (s: string) => b.quote(s);
  const table = b.table(ref),
    name = b.table({ schema: ref.schema, table: ref.objectName });
  let statements: string[];
  if (engine === 'mysql' && ref.kind === 'index') {
    assertSingleStatement(sql, engine, detail.mysqlNoBackslashEscapes);
    const tokens = sqlTokens(sql, engine, detail.mysqlNoBackslashEscapes);
    let i = 0;
    if (['UNIQUE', 'FULLTEXT', 'SPATIAL'].some((word) => keyword(tokens[i], word))) i++;
    if (
      !(keyword(tokens[i], 'KEY') || keyword(tokens[i], 'INDEX')) ||
      tokens[i + 1]?.value !== ref.objectName
    )
      throw new Error('Keep the original index name.');
    // A clause must not append another ALTER TABLE action at its outer level.
    let depth = 0;
    for (const token of tokens) {
      if (keyword(token, '(')) depth++;
      if (keyword(token, ')')) depth--;
      if (depth === 0 && keyword(token, ','))
        throw new Error('Only one index clause is permitted.');
    }
    statements = [
      `ALTER TABLE ${table} DROP INDEX ${q(ref.objectName)}, ADD ${sql.trim().replace(/;\s*$/, '')}`,
    ];
  } else {
    const header = objectHeader(sql, engine, ref.kind);
    if (
      !sameIdentifier(header.name, ref.schema, ref.objectName) ||
      !sameIdentifier(header.table, ref.schema, ref.table)
    )
      throw new Error('Keep the original object name, schema and target table.');
    if (ref.kind === 'index') {
      assertSingleStatement(sql, engine);
      // SQL Server accepts multiple statements without semicolons. An index
      // definition cannot carry a second batch command under a DDL approval.
      const forbidden = new Set(
        'CREATE ALTER DROP TRUNCATE INSERT UPDATE DELETE MERGE EXEC EXECUTE SELECT USE SET GRANT REVOKE DENY DECLARE PRINT RAISERROR THROW WAITFOR DBCC BACKUP RESTORE KILL BEGIN COMMIT ROLLBACK IF WHILE GOTO RETURN BREAK CONTINUE BULK SHUTDOWN CHECKPOINT RECONFIGURE'.split(
          ' ',
        ),
      );
      if (
        ['sqlserver', 'sybase'].includes(engine) &&
        header.tokens.some(
          (token) =>
            token.start >= header.tableEnd &&
            !token.quoted &&
            forbidden.has(token.value.toUpperCase()),
        )
      )
        throw new Error('Only one index definition is permitted.');
    } else if (engine === 'sqlite') assertSqliteTrigger(sql);
    else if (engine === 'postgres') assertSingleStatement(sql, engine);
    // Resolve unqualified input to the tab's scope, never the connection default.
    const canonicalName =
      engine === 'postgres' || (['sqlserver', 'sybase'].includes(engine) && ref.kind === 'index')
        ? q(ref.objectName)
        : name;
    const canonicalTable = engine === 'sqlite' ? q(ref.table) : table;
    sql =
      sql.slice(0, header.nameStart) +
      canonicalName +
      sql.slice(header.nameEnd, header.tableStart) +
      canonicalTable +
      sql.slice(header.tableEnd);
    if (engine === 'sybase') {
      const create = header.tokens[0];
      statements =
        ref.kind === 'trigger'
          ? [sql.slice(0, create.start) + 'CREATE OR REPLACE' + sql.slice(create.end)]
          : [`DROP INDEX ${table}.${q(ref.objectName)}`, sql];
    } else if (engine === 'sqlserver') {
      const create = header.tokens[0];
      statements = [
        ref.kind === 'trigger' ? sql.slice(0, create.start) + 'ALTER' + sql.slice(create.end) : sql,
      ];
      if (
        ref.kind === 'index' &&
        detail.indexOptions?.method === 'CLUSTERED' &&
        header.tokens.some((t) => keyword(t, 'NONCLUSTERED'))
      ) {
        const tokens = sqlTokens(sql, engine);
        const setting = tokens.findIndex(
          (t, i) =>
            keyword(t, 'DROP_EXISTING') &&
            keyword(tokens[i + 1], '=') &&
            keyword(tokens[i + 2], 'ON'),
        );
        if (setting >= 0)
          sql =
            sql.slice(0, tokens[setting + 2].start) + 'OFF' + sql.slice(tokens[setting + 2].end);
        statements = [`DROP INDEX ${q(ref.objectName)} ON ${table}`, sql];
      }
    } else {
      const drop =
        ref.kind === 'trigger' && engine === 'postgres'
          ? `DROP TRIGGER ${q(ref.objectName)} ON ${table}`
          : `DROP ${ref.kind.toUpperCase()} ${name}`;
      statements = [drop, sql];
    }
  }
  return {
    statements: [...detail.prefix, ...statements, ...detail.suffix],
    atomic: !['mysql', 'sybase'].includes(engine),
    notice: detail.notice,
  };
}

const pendingEdits = new WeakMap<SqlAdapter, Promise<unknown>>();
export async function applyObjectChange(
  adapter: SqlAdapter,
  connection: Connection,
  ref: ObjectRef,
  sql: string | IndexOptions,
  version: string,
  timeout: number,
) {
  const previous = pendingEdits.get(adapter) ?? Promise.resolve();
  const current = previous
    .catch(() => undefined)
    .then(() => applyObjectChangeNow(adapter, connection, ref, sql, version, timeout));
  pendingEdits.set(adapter, current);
  try {
    return await current;
  } finally {
    if (pendingEdits.get(adapter) === current) pendingEdits.delete(adapter);
  }
}
async function applyObjectChangeNow(
  adapter: SqlAdapter,
  connection: Connection,
  ref: ObjectRef,
  sql: string | IndexOptions,
  version: string,
  timeout: number,
) {
  const detail = await readObjectDefinition(adapter, connection, ref);
  if (detail.version !== version)
    throw new Error('The object changed since it was loaded. Refresh before applying changes.');
  const plan = planObjectChange(detail, ref, sql);
  if (connection.engine === 'mysql') {
    // This path needs a dedicated pooled session, including restoration and
    // original session settings. MysqlAdapter implements it explicitly.
    if (!('replaceObject' in adapter))
      throw new Error('Object editing is not supported by this adapter.');
    await (
      adapter as SqlAdapter & {
        replaceObject(statements: string[], restore: string[], timeout: number): Promise<void>;
      }
    ).replaceObject(plan.statements, ref.kind === 'trigger' ? detail.restore : [], timeout);
  } else {
    if (!adapter.executeDdl) throw new Error('Object editing is not supported by this adapter.');
    await adapter.executeDdl(plan.statements, timeout);
  }
  try {
    return await readObjectDefinition(adapter, connection, ref);
  } catch (error) {
    throw new Error(
      `Changes were applied, but reloading the definition failed. Refresh this tab. ${(error as Error).message}`,
    );
  }
}
